### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by VladShcherbin** [citycide/trilogy#16]
Unfortunately, http://trilogy.js.org/ is not working.

**Comment by citycide** [comment]
Thanks - unfortunately it's due to JS.org having not accepted my domain request [dns.js.org/#1003](https://github.com/js-org/dns.js.org/pull/1003) quite yet. Once that PR merges the site should be online. I didn't expect there to be such a delay without a response.

Sorry for the inconvenience. In the meantime check out the `docs` folder in the repo for the raw markdown files. Just be aware that links to other parts of the docs won't work.

**Comment by VladShcherbin** [comment]
I guess it's working now, thanks ;)

**Comment by citycide** [comment]
Yep - it's been merged so we have go for liftoff! :rocket: Thanks for reporting!
