### ISSUE TITLE
`find` accept Array

### ISSUE THREAD

**Issue by jonataswalker** [citycide/trilogy#32]
How about `find` accept an array?

Let's say I want `id` and `name` from a table. Right now it's not that hard with `knex.raw`:

```javascript
const query = db.knex(TABLE.CHILD)
  .where({ fatherId: id })
  .select('id', 'name')
  .orderBy(sortBy, order);
db.raw(query, true)
  .then(result => resolve(result))
  .catch(e => reject(e));
```

But it could be:

```javascript
const model = db.model(TABLE.CHILD);
return model.find(['id', 'name'], { fatherId: id });
```

**Comment by citycide** [comment]
I'm open to it but I'm not sure I'm sold. It can be done without adding it trilogy like this:

```js
const array = await model.find({ fatherId: id })
// -> [{ id: 1, name: 'one', other: 'stuff' }, { id: 2, name: 'two', other: 'stuff' }]

const { id, name } = array[0]
const mapped = array.map(({ id, name }) => ({ id, name }))
// -> [{ id: 1, name: 'one' }, { id: 2, name: 'two' }]
```

It seems easy enough to pull those out or map over the result to do this outside trilogy, especially if you use something like lodash / ramda `pick`. Unless this kind of select improves the actual query performance I'm just not entirely convinced yet.

**Comment by jonataswalker** [comment]
Yeah, I was just thinking about not pulling all the unneeded columns (maybe this is irrelevant data).

Your solution is good enough.

**Comment by citycide** [comment]
I think I'll reopen - I'm going to look into the performance considerations and weight the amount of code needed on either side (core vs. userland).

**Comment by jonataswalker** [comment]
All right. Thank you.

**Comment by citycide** [comment]
I've looked into this and the performance angle doesn't offer a significant advantage. As for code needed, adding it to core would be kind of non-trivial because `find()` and `findOne()` can both be called without a column at all. Differentiating between the `column` and `criteria` parameters is easy right now because `criteria` is either an Object or an Array, while `column` can only be string. If `column` can also be an Array that introduces ambiguity and that's a route I think I'd like to avoid.
