### ISSUE TITLE
Inject function in sql

### ISSUE THREAD

**Issue by jonataswalker** [citycide/trilogy#35]
I see that sql.js has a `create_function` that should/could work like this:

```javascript
const sum = (a) => a + 10;
db.create_function('sum', sum);

db.knex('some-table')
  .select('sum(col) AS foo');
```

However this is not possible. The `create_function` is available only if I use:

```javascript
const client = await db.pool.acquire(); // `acquire` is from generic-pool
client.create_function('sum', sum);

const query = db.knex('some-table')
  .select('sum(col) AS foo');

const res = await db.raw(query, true);
console.log('res', res); // never reach this log
db.pool.release(client);
```

If I use another approach:

```javascript
  return new Promise((resolve, reject) => {
    db.pool.acquire().then(client => {
      var sum = a => a + '...';
      client.create_function('sum', sum);
      const query = db.knex('some-table').select(db.knex.raw('sum(valorParcela)'));
      const res = db.raw(query, true);
      db.pool.release(client);
      resolve(res);
    });
  });
```

Then I get `Error: no such function: sum` which looks obvious because of `db.knex.raw`.

Wow, that was long. Maybe was easier if you expose the `sql.js` client?

**Comment by citycide** [comment]
Is it `sum` that you're interested in specifically or is that just a contrived example? For `sum` it would be easier to use `knex('some-table').sum('valorPacela')` and I think I was eventually going to add that along with `avg` since we have `min` & `max` already.

As for exposing the client... that doesn't seem natural. I really think of trilogy handling the broader database concepts moreso than custom functions, and knex for example doesn't expose its driver instances to you. I would also like to think that you could accomplish the same thing with a different approach, like various built-in sqlite functions, knex methods, or just processing the data after you grab it.

**Comment by jonataswalker** [comment]
Yeah I can process data after loaded, I was trying to avoid this since sqlite (and sql.js) allows you to create a function and use it on query.

The `sum` function is not what I'm looking for, was just for the example.

**Comment by citycide** [comment]
Closing, but maybe in the future I'll reconsider so thanks for the suggestion. Native sqlite module doesn't have this method so there'd be no parity between the two backends, and I think there are other ways to do similar things.
